[metadata]
name = "mmm-package-example"
version = "0.1.0"
description = "An example package for mimium/mmmpm"
authors = ["Shinichi Tanaka <shinichi.tanaka45@gmail.com>"]
license = "ISC"

[package]
entrypoint = "main.mmm"
